name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install
      - name: Prettier
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: prettier:check
      - name: ESLint
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: lint
      - name: Bundle
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: bundle
